### ISSUE TITLE
ModuleNotFoundError: No module named 'ovos_skill_homescreen.skill'

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/skill-ovos-homescreen#39]
Pip installed give the below error;

```
2022-10-08 17:42:40.861 - OVOS - ovos_plugin_manager.utils:find_plugins:85 - ERROR - Failed to load plugin entry point ovos-skill-homescreen.openvoiceos = ovos_skill_homescreen:OVOSHomescreenSkill
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ovos_plugin_manager/utils/__init__.py", line 83, in find_plugins
    entrypoints[entry_point.name] = entry_point.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2458, in load
    return self.resolve()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2464, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.10/site-packages/ovos_skill_homescreen/__init__.py", line 28, in <module>
    from .skill import (DashboardHandler,
ModuleNotFoundError: No module named 'ovos_skill_homescreen.skill'
```

**Comment by builderjer** [comment]
I had this error also, and mentioned the fix [here](https://matrix.to/#/!QMaxYxzZZsZPCUgTZw:matrix.org/$IdRWq1T-7XNoQTpbFJaBZ8MbIV0aKTH3rZO4X9toGD4?via=matrix.org&via=matrix.strongthany.cc&via=krbel.duckdns.org) in the chats
