### ISSUE TITLE
Unable to upload the QML files to GUI

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-homescreen#89]
```
3-07-29 17:13:04.538 - skills - ovos_core.skill_manager:handle_gui_connected:289 - DEBUG - GUI Connected
2023-07-29 17:13:04.544 - skills - ovos_utils.gui:upload_gui_pages:648 - DEBUG - No UI resources to upload
2023-07-29 17:13:04.545 - skills - ovos_utils.gui:upload_gui_pages:663 - DEBUG - Requested upload resources for: qt5
exception calling callback for <Future at 0x7f24fc2e3950 state=finished raised ConnectionResetError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/gui.py", line 679, in upload_gui_pages
    self.bus.emit(message.forward("gui.page.upload",
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 170, in emit
    self.client.send(message.serialize())
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 249, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
        ^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 170, in send
    return _send()
           ^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 147, in _send
    return sock.send(data)
           ^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2023-07-29 17:13:05.885 - skills - ovos_bus_client.client.client:on_error:112 - ERROR - === BrokenPipeError(32, 'Broken pipe') ===
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 428, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 80, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 437, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 423, in recv_data_frame
    self.send_close()
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 461, in send_close
    self.send(struct.pack('!H', status) + reason, ABNF.OPCODE_CLOSE)
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
        ^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 170, in send
    return _send()
           ^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 147, in _send
    return sock.send(data)
           ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2023-07-29 17:13:05.886 - skills - ovos_bus_client.client.client:on_error:119 - ERROR - Exception closing websocket at ws://0.0.0.0:8181/core: [Errno 32] Broken pipe
2023-07-29 17:13:05.886 - skills - ovos_bus_client.client.client:on_error:121 - WARNING - Message Bus Client will reconnect in 5.0 seconds.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/util/scheduler.py", line 142, in run
    self.check_state()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/util/scheduler.py", line 176, in check_state
    self.bus.emit(msg)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 170, in emit
    self.client.send(message.serialize())
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_app.py", line 249, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
        ^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 170, in send
    return _send()
           ^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/websocket/_socket.py", line 147, in _send
    return sock.send(data)
           ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by goldyfruit** [comment]
Same behaviour with `homescreen-lite`.

**Comment by goldyfruit** [comment]
Here are the messages received on message bus:

```
2023-07-29 17:25:43.802 - bus - ovos_messagebus.event_handler:on_message:37 - DEBUG - {"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {"source": "skill-ovos-homescreen.openvoiceos", "destination": ["gui"], "session": {"active_skills": [], "utterance_states": {}, "session_id": "63877afa-b882-4296-92c0-46da7815661f", "history": [[{"type": "gui.status.request", "data": {}, "context": {}}, 1690665943.5831134], [{"type": "mycroft.internet.connected", "data": {}, "context": {}}, 1690665943.7590551], [{"type": "mycroft.skills.error", "data": {"internet_loaded": false, "network_loaded": false}, "context": {}}, 1690665943.759478], [{"type": "mycroft.skills.initialized", "data": {}, "context": {}}, 1690665943.7596097], [{"type": "mycroft.skills.trained", "data": {}, "context": {}}, 1690665943.768204], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8011737]], "lang": "en-us", "valid_languages": ["en-us"], "context": {"timeout": 101439956340, "frame_stack": []}}}}

2023-07-29 17:25:43.804 - bus - ovos_messagebus.event_handler:on_message:37 - DEBUG - {"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {"source": "skill-ovos-homescreen.openvoiceos", "destination": ["gui"], "session": {"active_skills": [], "utterance_states": {}, "session_id": "63877afa-b882-4296-92c0-46da7815661f", "history": [[{"type": "mycroft.internet.connected", "data": {}, "context": {}}, 1690665943.7590551], [{"type": "mycroft.skills.error", "data": {"internet_loaded": false, "network_loaded": false}, "context": {}}, 1690665943.759478], [{"type": "mycroft.skills.initialized", "data": {}, "context": {}}, 1690665943.7596097], [{"type": "mycroft.skills.trained", "data": {}, "context": {}}, 1690665943.768204], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8011737], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8029928]], "lang": "en-us", "valid_languages": ["en-us"], "context": {"timeout": 101439956340, "frame_stack": []}}}}

2023-07-29 17:25:43.805 - bus - ovos_messagebus.event_handler:on_message:37 - DEBUG - {"type": "gui.request_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos", "framework": "qt5"}, "context": {"source": ["skills", "PHAL"], "destination": "gui", "session": {"active_skills": [], "utterance_states": {}, "session_id": "63877afa-b882-4296-92c0-46da7815661f", "history": [[{"type": "gui.status.request", "data": {}, "context": {}}, 1690665943.5831134], [{"type": "mycroft.internet.connected", "data": {}, "context": {}}, 1690665943.7590551], [{"type": "mycroft.skills.error", "data": {"internet_loaded": false, "network_loaded": false}, "context": {}}, 1690665943.759478], [{"type": "mycroft.skills.initialized", "data": {}, "context": {}}, 1690665943.7596097], [{"type": "mycroft.skills.trained", "data": {}, "context": {}}, 1690665943.768204], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8011737]], "lang": "en-us", "valid_languages": ["en-us"], "context": {"timeout": 101439956340, "frame_stack": []}}}}

2023-07-29 17:25:43.807 - bus - ovos_messagebus.event_handler:on_message:37 - DEBUG - {"type": "gui.request_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos", "framework": "qt5"}, "context": {"source": ["skills", "PHAL"], "destination": "gui", "session": {"active_skills": [], "utterance_states": {}, "session_id": "63877afa-b882-4296-92c0-46da7815661f", "history": [[{"type": "mycroft.internet.connected", "data": {}, "context": {}}, 1690665943.7590551], [{"type": "mycroft.skills.error", "data": {"internet_loaded": false, "network_loaded": false}, "context": {}}, 1690665943.759478], [{"type": "mycroft.skills.initialized", "data": {}, "context": {}}, 1690665943.7596097], [{"type": "mycroft.skills.trained", "data": {}, "context": {}}, 1690665943.768204], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8011737], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8029928]], "lang": "en-us", "valid_languages": ["en-us"], "context": {"timeout": 101439956340, "frame_stack": []}}}}

2023-07-29 17:25:43.819 - bus - ovos_messagebus.event_handler:on_message:37 - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/take.screenshot.intent", "samples": ["take screenshot", "take a screenshot"], "name": "skill-ovos-homescreen.openvoiceos:take.screenshot.intent", "lang": "en-us"}, "context": {"skill_id": "skill-ovos-homescreen.openvoiceos", "session": {"active_skills": [], "utterance_states": {}, "session_id": "63877afa-b882-4296-92c0-46da7815661f", "history": [[{"type": "mycroft.skills.error", "data": {"internet_loaded": false, "network_loaded": false}, "context": {}}, 1690665943.759478], [{"type": "mycroft.skills.initialized", "data": {}, "context": {}}, 1690665943.7596097], [{"type": "mycroft.skills.trained", "data": {}, "context": {}}, 1690665943.768204], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8011737], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8029928], [{"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/take.screenshot.intent", "samples": ["take screenshot", "take a screenshot"], "name": "skill-ovos-homescreen.openvoiceos:take.screenshot.intent", "lang": "en-us"}, "context": {}}, 1690665943.8179204]], "lang": "en-us", "valid_languages": ["en-us"], "context": {"timeout": 101439956340, "frame_stack": []}}}}

2023-07-29 17:25:43.828 - bus - ovos_messagebus.event_handler:on_message:37 - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/change.wallpaper.intent", "samples": ["change current wallpaper", "change the wallpaper", "change homescreen wallpaper", "change wallpaper"], "name": "skill-ovos-homescreen.openvoiceos:change.wallpaper.intent", "lang": "en-us"}, "context": {"skill_id": "skill-ovos-homescreen.openvoiceos", "session": {"active_skills": [], "utterance_states": {}, "session_id": "63877afa-b882-4296-92c0-46da7815661f", "history": [[{"type": "mycroft.skills.initialized", "data": {}, "context": {}}, 1690665943.7596097], [{"type": "mycroft.skills.trained", "data": {}, "context": {}}, 1690665943.768204], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8011737], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8029928], [{"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/take.screenshot.intent", "samples": ["take screenshot", "take a screenshot"], "name": "skill-ovos-homescreen.openvoiceos:take.screenshot.intent", "lang": "en-us"}, "context": {}}, 1690665943.8179204], [{"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/change.wallpaper.intent", "samples": ["change current wallpaper", "change the wallpaper", "change homescreen wallpaper", "change wallpaper"], "name": "skill-ovos-homescreen.openvoiceos:change.wallpaper.intent", "lang": "en-us"}, "context": {}}, 1690665943.826496]], "lang": "en-us", "valid_languages": ["en-us"], "context": {"timeout": 101439956340, "frame_stack": []}}}}

2023-07-29 17:25:43.841 - bus - ovos_messagebus.event_handler:on_message:37 - DEBUG - {"type": "mycroft.mark2.register_idle", "data": {"name": "OVOSHomescreen", "id": "skill-ovos-homescreen.openvoiceos"}, "context": {"skill_id": "skill-ovos-homescreen.openvoiceos", "session": {"active_skills": [], "utterance_states": {}, "session_id": "63877afa-b882-4296-92c0-46da7815661f", "history": [[{"type": "mycroft.skills.trained", "data": {}, "context": {}}, 1690665943.768204], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8011737], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8029928], [{"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/take.screenshot.intent", "samples": ["take screenshot", "take a screenshot"], "name": "skill-ovos-homescreen.openvoiceos:take.screenshot.intent", "lang": "en-us"}, "context": {}}, 1690665943.8179204], [{"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/change.wallpaper.intent", "samples": ["change current wallpaper", "change the wallpaper", "change homescreen wallpaper", "change wallpaper"], "name": "skill-ovos-homescreen.openvoiceos:change.wallpaper.intent", "lang": "en-us"}, "context": {}}, 1690665943.826496], [{"type": "mycroft.mark2.register_idle", "data": {"name": "OVOSHomescreen", "id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8393734]], "lang": "en-us", "valid_languages": ["en-us"], "context": {"timeout": 101439956340, "frame_stack": []}}}}

2023-07-29 17:25:43.864 - bus - ovos_messagebus.event_handler:on_message:37 - DEBUG - {"type": "mycroft.scheduler.schedule_event", "data": {"time": 1690665960.0, "event": "skill-ovos-homescreen.openvoiceos:skill-ovos-homescreen.openvoiceosupdate_dt", "repeat": 10, "data": {}}, "context": {"skill_id": "skill-ovos-homescreen.openvoiceos", "session": {"active_skills": [], "utterance_states": {}, "session_id": "63877afa-b882-4296-92c0-46da7815661f", "history": [[{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8011737], [{"type": "gui.volunteer_page_upload", "data": {"skill_id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8029928], [{"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/take.screenshot.intent", "samples": ["take screenshot", "take a screenshot"], "name": "skill-ovos-homescreen.openvoiceos:take.screenshot.intent", "lang": "en-us"}, "context": {}}, 1690665943.8179204], [{"type": "padatious:register_intent", "data": {"file_name": "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_homescreen/locale/en-us/change.wallpaper.intent", "samples": ["change current wallpaper", "change the wallpaper", "change homescreen wallpaper", "change wallpaper"], "name": "skill-ovos-homescreen.openvoiceos:change.wallpaper.intent", "lang": "en-us"}, "context": {}}, 1690665943.826496], [{"type": "mycroft.mark2.register_idle", "data": {"name": "OVOSHomescreen", "id": "skill-ovos-homescreen.openvoiceos"}, "context": {}}, 1690665943.8393734], [{"type": "mycroft.scheduler.schedule_event", "data": {"time": 1690665960.0, "event": "skill-ovos-homescreen.openvoiceos:skill-ovos-homescreen.openvoiceosupdate_dt", "repeat": 10, "data": {}}, "context": {}}, 1690665943.8625586]], "lang": "en-us", "valid_languages": ["en-us"], "context": {"timeout": 101439956340, "frame_stack": []}}}}
```

**Comment by NeonDaniel** [comment]
If homescreen lite also has the same symptom, then I think this issue may belong in `ovos_bus_client`, where the exception is first seen in an OVOS package

**Comment by JarbasAl** [comment]
This has been diagnosed as max message size exceeded, the upload of pages needs to keep messages under 10MB, there's a workaround in ovos GUI repo to make current implementation work until this is done
